apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ tpl .Values.cdc.hydraCdc.name . }}
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ tpl .Values.cdc.hydraCdc.name . }}
      app.kubernetes.io/instance: {{ .Values.cdc.appId }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: {{ tpl .Values.cdc.hydraCdc.name . }}
        app.kubernetes.io/instance: {{ .Values.cdc.appId }}
        app.kubernetes.io/name: {{ tpl .Values.cdc.hydraCdc.name . }}
    spec:
      containers:
      - env:
        - name: HTTP_PORT
          value: "9100"
        - name: KAFKA_TRANSACTIONS_HOST
          value: {{ tpl .Values.cdc.kafka.kafkaBootstrapHost . }}
        - name: KAFKA_CDC_HOST
          value: {{ tpl .Values.cdc.kafka.kafkaBootstrapHost . }}
        - name: HYDRA_TRANSACTIONS_TOPIC
          value: {{ tpl .Values.cdc.hydraCluster.transactionsTopic . }}
        - name: HYDRA_CDC_TOPIC
          value: {{ tpl .Values.cdc.hydraCdc.topic . }}
        - name: HYDRA_URLS
          value: {{ tpl .Values.cdc.hydraCluster.sessionUrl . }}
        - name: APP_ID
          value: {{ tpl .Values.cdc.appId . }}
        - name: TRACING_FORMAT
          value: json
        - name: RUST_LOG
          value: info,hydra_cdc=debug
        - name: HEARTBEAT_SYSTEM_COLLECTION
          value: __heartbeat
        image: {{ tpl .Values.cdc.images.hydraCdc.name . }}
        imagePullPolicy: {{ .Values.cdc.images.hydraCdc.pullPolicy }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: hydra-cdc
        ports:
        - containerPort: 9100
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readiness
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 2G
          requests:
            cpu: 100m
            memory: 1G
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      {{- with .Values.cdc.images.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      preemptionPolicy: PreemptLowerPriority
      priority: 0
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 300
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 300
